language: swift
matrix:
    include:
        - osx_image: xcode10.2

before_install:
    - echo "git \"file://$($(dirname $0); pwd)\"" >> Cartfile
    - brew update
#   - brew install carthage
    - brew outdated swiftlint || brew upgrade swiftlint
    - carthage update --platform iOS

script:
    - xcodebuild -scheme RxScreenProtectKit -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' build test
    - swiftlint

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 31ae53bc-db30-4cd8-a1cf-7bca2026a5ea

# https://docs.travis-ci.com/user/reference/osx/#xcode-version
# https://docs.travis-ci.com/user/languages/objective-c/

