language: swift
matrix:
    include:
        - osx_image: xcode11.4

before_install:
#   - echo "git \"file://$($(dirname $0); pwd)\"" >> Cartfile
    - cat Cartfile
    - brew update
    - brew outdated swiftlint || brew upgrade swiftlint
    - carthage update --platform iOS

script:
    - xcodebuild -scheme RxScreenProtectKit -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone 11 Pro' -configuration Debug test | xcpretty -c
    - swiftlint

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 31ae53bc-db30-4cd8-a1cf-7bca2026a5ea

# https://docs.travis-ci.com/user/reference/osx/#xcode-version
# https://docs.travis-ci.com/user/languages/objective-c/

